<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 21" tests="1" total_time="Finished in: 0.00 secs."/>
    <test location="/home/estudiante/eclipse-workspace/Ejercicios3/tests/tests.py" status="error" test="Test.testData" time="">
        <stdout/>
        <stderr><![CDATA[Traceback (most recent call last):
  File "/home/estudiante/eclipse-workspace/Ejercicios3/tests/tests.py", line 51, in testData
    self.assert_(ejercicios.numberOfNumbers(29)==2)
AttributeError: module 'ejercicios' has no attribute 'numberOfNumbers'
]]></stderr>
    </test>
    <launch mode="run">
        <launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Ejercicios3 tests.py"/>
]]></launch_memento>
    </launch>
</pydev-testsuite>
